spring:
  kafka:
    # 配置kafka连接地址
    bootstrap-servers: 192.168.0.5:9092
    # 配置生产者
    #producer:
    # 配置消费者
    consumer:
      auto-offset-reset: earliest
    template:
      default-topic: hello-topic

