CREATE TABLE EMP (
    EMPNO INT PRIMARY KEY AUTO_INCREMENT COMMENT '员工编号',
    ENAME varchar(15) NOT NULL COMMENT '员工姓名',
    JOB varchar(15) NOT NULL COMMENT '员工职位',
    HIREDATE date DEFAULT NULL COMMENT '入职时间',
    SAL double(20,2) DEFAULT '0.00' COMMENT '薪资',
    COMM double(20,2) DEFAULT NULL COMMENT '年奖金',
    DEPTNO int(20) DEFAULT NULL COMMENT '部门编号'
)ENGINE = MyISAM DEFAULT CHARSET=utf8;