server:
  port: 8080

# spring本身并不提供websocket相关配置，下面这些配置都是我们自定义的
spring:
  websocket:
    # websocket端点路径前缀
    endpoint-path-prefix: /websocket-spring-ws
    # 允许的跨域来源
    allowed-origins:
      - "*"           # 原生websocket用到
      - "http://*"    # sockjs用到
      - "http://*:*"    # sockjs用到
    # 是否启用sockjs
    enable-sockjs: false
