server:
  port: 8080
person:
  lastName: zhangsan
  age: 18
  boss: false
  birthday: 2017/12/12
  maps:
    k1: v1
    k2: 12
  lists:
    - lisi
    - zhaoliu
  dog:
    name: xiaogou
    age: 5
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
logging:
  config:
    classpath:logback.xml

#会打印自动配置信息
debug: false
---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8084
spring:
  profiles: prod