use javaee;
CREATE TABLE TBL_EMPLOYEE (
    ID VARCHAR(32) PRIMARY KEY,
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    GENDER VARCHAR(50)
);
INSERT INTO TBL_EMPLOYEE (ID, LAST_NAME, EMAIL, GENDER) VALUES ('1', 'ZHANGSAN', '1458687169@QQ.COM', '男');

--使用id和TBL_EMPLOYEE中id相关联
CREATE TABLE TBL_DEPARTMENT (
    ID VARCHAR(32) PRIMARY KEY,
    DNAME VARCHAR(50)
);