CREATE TABLE TBL_EMPLOYEE (
    ID VARCHAR2(32) PRIMARY KEY,
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(50),
    GENDER VARCHAR2(50)
);
INSERT INTO TBL_EMPLOYEE ("ID", "LAST_NAME", "EMAIL", "GENDER") VALUES ('1', 'ZHANGSAN', '1458687169@QQ.COM', '男');

CREATE SEQUENCE TBL_EMPLOYEE_SEQ
MINVALUE 1  --最小值
--NOMAXVALUE  --不设置最大值(由机器决定)，或 根据表字段的值范围设置 MAXVALUE
MAXVALUE 9999999  -- 最大值
START WITH 1   --从1开始计数，数值可变
INCREMENT BY 1  --每次加1，数值可变
NOCYCLE  --一直累加，不循环；CYCLE：达到最大值后，将从头开始累加
NOCACHE;

--使用id和TBL_EMPLOYEE中id相关联
CREATE TABLE TBL_DEPARTMENT (
    ID VARCHAR2(32) PRIMARY KEY,
    DNAME VARCHAR2(50)
);