version: V1.0

user:
  username: 张三
  password: zhangsan
library:
  location: 陕西省图书馆
  books:
    - name: 钢铁是怎样练成的
      description: 保尔·柯察金历险记
    - name: 小王子
      description: 小王子历险记
    - name: 鲁滨孙漂流记
      description: 鲁滨孙历险记

debug: false

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

logging:
  config:
    classpath:logback.xml
