server:
  port: 8080

# spring本身并不提供websocket相关配置，下面这些配置都是我们自定义的
spring:
  websocket:
    # websocket端点路径前缀
    endpoint-path-prefix: /websocket-spring-sockjs
    # 允许的跨域来源
    allowed-origins:
      - http://*   # sockjs用到
    # 是否启用sockjs
    enable-sockjs: true