server:
  port: 8080
management:
  endpoint:
    shutdown:
      enabled: true #是否显示shutdown访问url,这个是远程关闭应用用的
    health:
      show-details: always  #显示健康具体信息  默认不会显示详细信息
  endpoints:
    enabled-by-default: true  #是否关闭所有端点访问,true:启用所有监控端点,false:不启用所有监控端点
    web:
      exposure:
        include: '*'  #代表开放所有页面节点  默认只开启了health、info两个节点
      base-path: /actuator #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      path-mapping:
        beans: new-beans  #自定义beans端点访问路径
  info:
    git:
      mode: full
info:   #访问http://localhost:8080/actuator/info 时显示的应用信息
  appid: hello
  apnname: actuator
  version: 1.0

spring:
  loging:
    level:
      org.bluebridge: debug
  redis:
    host: 127.0.0.1 #不启动redis,访问http://localhost:8080/actuator/health,可以监控到redis状态为 DOWN